Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.11/dist-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.11/dist-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.11/dist-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Tampilkan pusat cluster awal
centers_df = pd.DataFrame(scaler.inverse_transform(cntr), columns=feature_cols)
print(tabulate(centers_df, headers="keys", tablefmt="psql", showindex=True))

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-26-69a8e239b1ca>[0m in [0;36m<cell line: 0>[0;34m()[0m
[1;32m      1[0m [0;31m# Tampilkan pusat cluster awal[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mcenters_df[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mDataFrame[0m[0;34m([0m[0mscaler[0m[0;34m.[0m[0minverse_transform[0m[0;34m([0m[0mcntr[0m[0;34m)[0m[0;34m,[0m [0mcolumns[0m[0;34m=[0m[0mfeature_cols[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mprint[0m[0;34m([0m[0mtabulate[0m[0;34m([0m[0mcenters_df[0m[0;34m,[0m [0mheaders[0m[0;34m=[0m[0;34m"keys"[0m[0;34m,[0m [0mtablefmt[0m[0;34m=[0m[0;34m"psql"[0m[0;34m,[0m [0mshowindex[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'cntr' is not defined

